server:
  port: 8088
  servlet:
    context-path: "/simple"

spring:
  application:
    name: portfolio-service

filter:
  bypass:
    authorization:
      - /internal/**
      - /api/v1/auth/**

jwt:
  secret: "jwtsecret"
  expire:
    access: 6000000
    refresh: 12000000

username-password:
  list:
    JOHN: "123"
    JANE: "XYZ"
    JACK: "QWE"




