server:
  port: 8088
  servlet:
    context-path: "/simple"

spring:
  application:
    name: auth-service

filter:
  bypass:
    authorization:
      - /internal/**
      - /v1/auth/**

jwt:
  secret: "jwtsecret"



